[package]
name = "blur_lang"
version = "0.1.1"
edition = "2021"
authors = ["Valery Shvets <seacrest@ukr.net>"]
description = "Language for JavaScript optimization"
homepage = "https://github.com/seacrst/blur_lang"
license = "MIT"
